### ISSUE TITLE
Difficult to add modes

### ISSUE THREAD

**Issue by wardy484** [thlorenz/brace#107] opened 2017-11-07 20:55 UTC
I have now successfully added a new "mode". 

However it proved very difficult to setup and debug. It would be great if it was possible to add a mode without having to fork the package.

**Comment by thlorenz** [comment] 2017-11-20 14:56
I'm not sure if that isn't an issue for the ace editor repo from which this one is derived.

**Comment by Seraf** [comment] 2017-11-21 09:07
Hello @wardy484,
I'm currently trying to add a mode also, but get some problem importing it.
I put my mode in `../vendor/editor/hcl` and I do an import on it.

Then, I try to use it with `.setMode('ace/mode/hcl')` but ace is trying to get this module through http.
Any idea please ?

**Comment by bgrayburn** [comment] 2017-11-21 16:14
not so hard to do in ace following these directions: https://github.com/ajaxorg/ace/wiki/Importing-.tmtheme-and-.tmlanguage-Files-into-Ace

**Comment by Seraf** [comment] 2017-11-21 16:23
The problem is about having to fork the library to include the language file in the modes.
Else, ACE will try to load it through http, but I personally wanted to be able to inject it through a require/import or something like that without exposing it through a http request

**Comment by bgrayburn** [comment] 2017-11-21 16:31
I'm struggling with this too, here's my next try, copying into the node_modules/brace/modes folder at build/run time. That way the language file lives in your repo. In so many ways this is gross, but looks like it really is a limitation of ace.

**Comment by thlorenz** [comment] 2017-11-21 17:16
OK so from that info seems like an ACE issue. Please file there and we can close it here ...

**Comment by JackuB** [comment] 2018-01-17 09:17
You can definitely add Modes without forking the package or doing something with node_modules.

The [`ace.define` syntax](https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode) is available even if you are using Webpack. Your custom Mode in a module should look like this:
https://gist.github.com/JackuB/3d589bd64dc96c1b18486baaaf58d910 Just be sure to also `require()` it.

_Shameless plug_: [wrote a few tips for writing custom Modes](https://medium.com/apiary-cafeteria/writing-custom-ace-editor-mode-5a7aa83dbe50) after struggling with it myself

**Comment by komali2** [comment] 2018-04-18 21:58
@JackuB if `require()` it, webpack can't find it, and complains.

**Comment by JackuB** [comment] 2018-04-18 22:01
@komali2 got a code sample?

**Comment by komali2** [comment] 2018-04-18 22:10
Yup one sec

**Comment by komali2** [comment] 2018-04-23 20:59
@JackuB unsure, we swapped from brace to ace, and following the steps in the linked issue, got it working

**Closed** 2021-03-16 14:35 UTC
Labels: question
