### ISSUE TITLE
How to Vim.defineEx ?

### ISSUE THREAD

**Issue by tylerlong** [thlorenz/brace#81] opened 2017-03-27 12:12 UTC
I have the following code with ACE which I want to migrate to brace:

```JavaScript
const Vim = ace.require('ace/keyboard/vim').CodeMirror.Vim
Vim.defineEx('write', 'w', (cm, input) => {
  console.log('write')
})
```

I cannot figure out the solution because `require('brace/keybinding/vim')` seems like an empty object

**Comment by thlorenz** [comment] 2017-03-27 13:40
please look at [this example](https://github.com/thlorenz/brace/blob/master/example/javascript-editor.js#L4) and it'll show you how you need to `require` things directly.
Just using `ace.require` won't work.

**Comment by tylerlong** [comment] 2017-03-28 01:00
I did look at that. And my last sentence said `require('brace/keybinding/vim')` seemed like an empty object.

**Comment by thlorenz** [comment] 2017-03-28 07:42
Just do it like in the example, it will be an empty object as the require just ensures that the binding file will be part of the bundle so that you can use it as [is shown here](https://github.com/thlorenz/brace/blob/master/example/javascript-editor.js#L9).

Just the Vim binding like in the example. Have you tried running the example and does that work for you? WRT code mirror API I don't know. Does that exact code work with ace itself even?

**Comment by tylerlong** [comment] 2017-03-28 10:15
My question is not how to enable Vim mode. Your example already shows how to do that and I did read your example.

I want to customize Vim commands such as `:w` to save the file. The code does with with ACE. http://stackoverflow.com/a/28084432/862862 I tried it myself and it does work. Problem is I don't know how to write similar code with brace.

**Comment by thlorenz** [comment] 2017-03-28 10:19
ah ok now I understand your problem, sorry for being slow.

I have no idea why this isn't working with brace as it is with ACE. It should.
Maybe we are missing some modules we need to pull in? Or are we still based on a version of ACE that doesn't have that feature?
We'd need to find out what part of ACE enables customizing Vim commands and make sure we pull those files in as well.

I personally have no bandwidth to look into that, but I'm reopening the issue. Hopefully someone can have a look, or if you have time to look into this, I'd greatly appreciate a PR :)

**Comment by exitface** [comment] 2017-04-05 05:09
Ran into the same problem myself, the solution is to use `ace.acequire` rather than `ace.require`:

```javascript
    const ace = require("brace")
    const Vim = ace.acequire('ace/keyboard/vim').CodeMirror.Vim

    Vim.defineEx('write', 'w', (cm, input) => {
      console.log('write')
    })
```

**Comment by matthijsgroen** [comment] 2017-10-14 05:09
This works for me:

```javascript
const ace = require("brace");
require('brace/keybinding/vim')

const editor = ace.edit("editor");

ace.config.loadModule("ace/keyboard/vim", module => {
  const VimApi = module.CodeMirror.Vim;
  VimApi.defineEx("write", "w", (cm, input) => {
    console.log("write");
  });
});
editor.setKeyboardHandler("ace/keyboard/vim");
```

**Comment by thlorenz** [comment] 2017-10-30 16:19
@matthijsgroen could you please create a wiki page [here](https://github.com/thlorenz/brace/wiki) so we can collect these _tricks_ and link to them from the readme? Just do `Add New Page`.
Thanks.

**Comment by thlorenz** [comment] 2017-10-30 16:20
Closing though since the issue is solved

**Closed by thlorenz** 2017-10-30 16:20 UTC
